version: '3'

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-opensearch-datasource
    networks:
      - opensearch-net
    restart: always

networks:
  opensearch-net:
    external:
      name: docker-composes_opensearch-net
