version: '3'
services:
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:latest
    container_name: logstash
    user: root
    volumes:
      # TODO: mount your pipeline directory into the container. USE ABSOLUTE PATH!
      - <ABS_PATH_TO_YOUR_PIPELINE_DIRECTORY>:/usr/share/logstash/pipeline
    ports:
      - 9400:9400
    environment:
      # TODO: set your opensearch username and password here.
      - OPENSEARCH_USER=<YOUR_USERNAME>
      - OPENSEARCH_PASSWORD=<YOUR_PASSWORD>
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external:
      name: docker-composes_opensearch-net
