version: '3'
services:
  logstash:
    image: opensearchproject/logstash-oss-with-opensearch-output-plugin:7.16.2
    container_name: logstash
    user: root
    volumes:
      - /home/wmarcoyu/logstash-pipeline:/usr/share/logstash/pipeline
    ports:
      - 9400:9400
    environment:
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: OpensearchInit2024
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external:
      name: docker-composes_opensearch-net
